
=== Soll-Stand Server-Infrastruktur

====
Welche Server Variante soll verwendet werden (lokale VM, physischer Server oder Cloud‑Instanz)?
 +
 +
 +
 +
 +
====

====
Welche Login-Methode soll verwendet werden (OpenID Connect, SAML, lokale Benutzer-/Passwortverwaltung)*
 +
 +
 +
 +
 +
====


====
Welche Modelle/Provider soll verwendet werden (Azure OpenAI, AWS Bedrock, Lokale Modelle) 
 +
 +
 +
 +
 +
====

====
Welche Use Cases werden benötigt?
 +
 +
 +
 +
 +
====

====
Welches Format wird für die Übergabe der Use Cases an Lieferant verwendet?
 +
 +
 +
 +
 +
====

====
Welche externen Systeme sollen angebunden werden?

|===
| System | Integrationstyp | Beschreibung | Erforderlich 

| Active Directory 	| LDAP	| Authentifizierung Benutzer aus AD |  
| Email Server 	| API | Integration Email über SMTP				|  
| SharePoint 	| API 	| Integration Dokumenten				| 
| SAP 	| API 	| Integration Daten					| 
|  	|  	| 					| 
|  	|  	| 					| 
|===
====

====
Welche Verbindungs-Methode soll verwendet werden (HTTP/S, Reverse Proxy, SSL-Zertifikate)?
Caddy mit Let's Encrypt (Reverse Proxy, Portfreigabe) +
DNS‑01 (öffentlich trusted, ohne Freigabe 80/443) +
ohne öffentlichen DNS (keine Portfreigabe) +
 +
 +
 +
 +
 +
====


====
Welche Lizenz ist erforderlich(Anzahl Nutzer, Gültigkeit von/bis)?
 +
 +
 +
 +
 +
====

====
Wer sind die initialen Admin-Nutzer(jeweils ADMIN_USERNAME und ADMIN_PASSWORD)?
 +
 +
 +
 +
 +
====