
== Soll-Stand Server-Infrastruktur

====
Welche Server Variante soll verwendet werden (lokale VM, physischer Server oder Cloud‑Instanz)?
 +
 +
 +
 +
 +
====
====
Ist Unterstützung bei der Einrichtung Server Variante notwendig (basic, middle, hight)?
 +
 +
 +
 +
 +
====
====
Welche Login-Methode soll verwendet werden (OpenID Connect, SAML, lokale Benutzer-/Passwortverwaltung)?
 +
 +
 +
 +
 +
====
====
Ist Unterstützung bei der Einrichtung Login-Methode notwendig (basic, middle, hight)?
 +
 +
 +
 +
 +
====
====
Welche LLM Modelle/Provider sollen verwendet werden (Azure OpenAI, AWS Bedrock, Lokale Modelle)?
 +
 +
 +
 +
 +
====
====
Ist Unterstützung bei der Einrichtung LLM Modelle/Provider notwendig (basic, middle, hight)?
 +
 +
 +
 +
 +
====
====
Welche Use Cases werden benötigt?
 +
 +
 +
 +
 +
====
====
Welches Format wird für die Übergabe der Use Cases an Lieferant verwendet?
 +
 +
 +
 +
 +
====
====
Welche externen Systeme sollen angebunden werden?
|===
| System | Integrationstyp | Beschreibung | Erforderlich 

| Active Directory 	| LDAP	| Authentifizierung Benutzer aus AD |  
| Email Server 	| API | Integration Email über SMTP				|  
| SharePoint 	| API 	| Integration Dokumenten				| 
| SAP 	| API 	| Integration Daten					| 
|  	|  	| 					| 
|  	|  	| 					| 
|===
====
====
Ist Unterstützung bei der Einrichtung externen Systeme notwendig (basic, middle, hight)?
 +
 +
 +
 +
 +
====
====
Welche eigenen Agenten (MCP-Server) sind notwendig?
 +
 +
 +
 +
 +
====
====
Welche Netzwerk-Methode soll verwendet werden (HTTP/S, Reverse Proxy, SSL-Zertifikate)? +
Caddy mit Let's Encrypt (Reverse Proxy, Portfreigabe) +
DNS‑01 (öffentlich trusted, ohne Freigabe 80/443) +
ohne öffentlichen DNS (keine Portfreigabe) +
 +
 +
 +
 +
 +
====
====
Ist Unterstützung bei der Einrichtung Netzwerk-Methode notwendig (basic, middle, hight)?
 +
 +
 +
 +
 +
====
====
Welche Lizenz ist erforderlich (Anzahl Nutzer, Gültigkeit von/bis)?
 +
 +
 +
 +
 +
====
====
Wer sind die initialen Admin-Nutzer?
 +
 +
 +
 +
 +
====