

=== RAG

==== Integriertes Dokumentenmanagementsystem

Das ist eine SQLight DB Anbindung in der systemseitig festgelegte Ordner und vom Kunden zu pflegende Dokumente gespeichert sind. 

==== Sharepoint Andindung API von Microsoft

Die Anbindung von Sharepoint muss über die API von Microsoft durch den Kunden erfolgen. 
In SharePoint werden einzelne Bereiche Sites genannt, diese entsprechen in etwa den Gruppen in Teams.
Aufruf des Listing z.B https://kunde.sharepoint.com/sites/

Dort wird die Application {application} als site registriert.

ifeval::[{big-output} == 1]

Ist die Applikation {application} nicht vorhanden, muss sie wie folgt registriert werden:


* 1.
* 2.
* 3.

Dadurch erhält die Application eine Application ID.
Zusätzlich müssen in der Application die ClientSecrets gesetzt werden.
z.B. "Sites.Read.All" oder "Sites.Selected"
Wird "Sites.Selected" gewählt, müssen die Zugriffsberechtigungen in Sharepoint granuliert werden.

endif::[]

Die erforderlichen Daten, für die Anbindung {application} an API von Microsoft durch den Kunden, sind:

* Tenant ID: Die ID des SharePoint-Mandanten, normalerweise eine GUID.
* Application ID: Die Client-ID der SharePoint-Anwendung mit den erforderlichen Berechtigungen (ClientSecrets) für den Datenzugriff.
* ClientSecrets: Die SharePoint-Application-Berechtigungen für den Datenzugriff.