
===== Applikation registrieren im Microsoft Entra Admin Center für SAML

*1. Anmeldung*

* Öffnen Microsoft Entra Admin Center: https://entra.microsoft.com
* Anmeldung mit einem Konto an, das über Administratorrechte verfügt.

*2. Neue App‑Registrierung anlegen*

* Navigieren zu *Entra ID → App‑Registrierungen*.
* Klicken auf *Neue Registrierung*.
* Anwendungsinformationen eingeben*

** *Name*: einen eindeutigen Namen wählen, z. B.: {application}-openid-app
** *Unterstützte Kontotypen*: Wählen wer die Anwendung nutzen darf. Standard: Nur mein Mandant (Single Tenant).
* Anwendungsinformationen eingeben:

** *Name*: einen eindeutigen Namen wählen, z. B.: {application}-email-app
** *Unterstützte Kontotypen*: Wählen wer die Anwendung nutzen darf. Standard: Nur mein Mandant (Single Tenant).
** *Redirect‑URI*: Eintrag Redirect‑URI, die identisch mit redirect_uri in der Datei init_config.yaml ist (für OIDC erforderlich).
* Klicken auf *Registrieren*

====== SAML-Konfiguration

*3. SAML als Authentifizierungsmethode aktivieren*

* Öffnen Entra ID → Enterprise applications → Ihre Anwendung → Single sign‑on
* Wählen SAML.
* Die Seite SAML-basierte Konfiguration öffnet sich.

*4. Grundlegende SAML‑Konfiguration*

* Bezeichner (Entity ID): Verwenden Sie die eindeutige Kennung aus dem Admin Center.
* Reply/Redirect‑URL: Muss identisch zur redirect_uri in der Datei init_config.yaml sein.

*5. Attribute & Claims einrichten*

* Damit die Anwendung stets aktuelle Benutzerdaten erhält, müssen Claims für folgende Werte eingerichtet werden:
** Vorname
** Nachname
** E‑Mail

Dies stellt sicher, dass die Anwendung {application} bei jeder Anmeldung die aktuellen Profildaten des Benutzers erhält.

*6. SAML‑Zertifikate (SAML Certificates)*

* Laden Sie die Datei Federation Metadata XML herunter.
* Speichern Sie die Datei im SHARED_FOLDER. Der Ablagepfad muss identisch zum Eintrag idp_metadata_path in init_config.yaml sein.

Die XML‑Datei enthält u. a.:

* Entity ID
* SSO‑URL
* Signatur‑Zertifikate

*7. Wichtige Konfigurationsdaten erfassen*

[.highlight]#Notieren bzw. kopieren Sie die folgenden Werte für init_config.yaml:#

** Anwendungs-ID (unter Übersicht): *Anwendungs-ID (Client)*
** Mandant-ID (unter Übersicht): *Verzeichnis-ID (Mandant)*
** geheimer Clientschlüssel (unter Übersicht): *Client-Secrets*, kann zeitlich begrenzt werden
** Redirect-URI: *Redirect‑URI* Umleitung nach erfolgreicher Anmeldung zu {application}









