
=== Allgemeine Vorrausetzungen

Dieses Kapitel beschreibt die technischen Grundanforderungen für den Betrieb von {application}. Die Anwendung wird vollständig beim Kunden betrieben und benötigt lediglich eine Linux‑Umgebung mit installiertem Docker.

==== Infrastruktur (VM oder Server)

Die Lösung wird auf einem *Linux‑basierten Server* bereitgestellt — entweder als *lokale VM*, physischer Server oder *Cloud‑Instanz*. +
Eine spezielle Cloud‑Integration ist *nicht erforderlich*, jeder Linux‑Server mit einer funktionierenden Docker‑Installation ist geeignet.

*Hinweis:* +
Eine dedizierte VM ist nicht zwingend notwendig. {application} kann auch auf einem bestehenden Linux‑Server betrieben werden, solange die Ressourcenanforderungen erfüllt sind.

===== Serveranforderungen

Für den produktiven Betrieb der Applikation {application} gelten folgende, lastbedingte Mindestanforderungen:

|===
|Level | Arbeitsspeicher (vRAM)|Prozessor (vCPU)|Speicher|Szenarien|Nutzer

|Entry Level (RAG, 8 GB RAM)
| 8 GB
| 4 vCPUs
| 250 GB SSD (virtueller NVMe/SSD-Speicher)
| Bis 100 MB Dokumente
| 1-5

|Mid-Tier Level (RAG, 32 GB RAM)
|32 GB
|8-12 vCPUs
|1 TB SSD (virtueller NVMe/SSD-Speicher)
|Bis 5 GB Dokumente
|10-50

|High-End Level (RAG, 64 GB RAM)
|64 GB
|16-32 vCPUs
|2 TB SSD (virtueller NVMe/SSD-Speicher)
|über 5 GB Dokumente
|50+
|===
 
==== Betriebssystem

Unterstützt werden:

* *Linux‑Distributionen*, bevorzugt *Ubuntu Server LTS (24.04)*
* Andere Distributionen sind in der Regel kompatibel und können auf Anfrage getestet werden.

Ubuntu wurde als Referenzsystem für Tests genutzt.

==== Docker-Umgebung

Die Bereitstellung erfolgt über *Docker*.

*Erforderliche Versionen:*

* *Docker Engine:* Version `>` 2.x

*Installation:* Der Kunde muss Docker auf dem Server installieren und konfigurieren.

Docker speichert Daten (Images, Container, Volumes) standardmäßig unter Linux im Verzeichnis `/var/lib/docker`. +
Volumes für persistente Daten liegen typischerweise in `/var/lib/docker/volumes`. +
Für den Betrieb empfehlen wir mindestens 20 GB Speicher für das Docker-Datenverzeichnis zur Verfügung stellen.

==== Gemeinsames Verzeichnis (SHARED_FOLDER)

Ein *beschreibbares Verzeichnis* auf dem Server für den Datenaustausch zwischen den Containern und für persistente Daten. Hier werden u. a. gespeichert:

* Dokumente
* Konfigurationsdateien
* Datenbank (SQLite)
* Vector‑Store (ChromaDB)

*Aufgabe des Kunden:* 
Bereitstellung eines Verzeichnisses (SHARED_FOLDER) mit ausreichenden Schreib-/Leserechten für die Docker-Container.
Da in diesem Verzeichnis Datenbank und Konfigurationsdateien enthalten sind, ist wachsender Speicherbedarf einzuplanen.







