
=== Installation und Konfiguration

==== Erstkonfiguration der Anwendung

Es wird ein *Konfigurationspaket* als ZIP-Datei zur Verfügung gestellt, die den Grundaufbau der Konfiguration des {application} enthält.
Diese enthält die folgende Dateistruktur:

```
|_docker-compose.yaml
|_.env.example
|_configuration/
  |_config.yaml
  |_init/
    |_init_config.yaml
    |_authorization_roles.yaml
```

Optional ist hier auch ein `Caddyfile.example` oder ein vorkonfiguriertes `Caddyfile` enthalten, das die Konfiguration des Reverse Proxy enthält.

Es sind folgende Initialkonfigurationen vorzunehmen:

- Erzeugung einer Datei `.env` auf Basis von `.env.example`
- gewählte Authentifizierung konfigurieren
- (optional) RAG-Ordner konfigurieren
- (optional) SharePoint-Anbindung konfigurieren
- (optional) Reverse Proxy konfigurieren

===== Umgebungsvariablen einrichten 

Die folgenden Werte sind konfigurierbar in der `.env` Datei

|===
| Variable | Pflicht | Beschreibung | Beispielwert(e)

| `SHARED_FOLDER`
| Ja
| Pfad für gemeinsames Verzeichnis
| `/opt/assist/shared`

| `JWT_SECRET_KEY`
| Required
| Hash for JWT creation (32-64 bytes)
| `hdhfh5jdnb7a9563b93f7099f6f0f4caa6cf63b88e8d3e7`

| `LOG_LEVEL`
| Nein
| Log-Level der Applikation (Standardwert: INFO)
| ERROR / WARNING / INFO

| `BRAVE_API_KEY`
| Nein
| API-Schlüssel für die Anbindung der Brave-Websuche
| 
|===

==== Deployment-Anleitung (Schritt-für-Schritt)

Das Deployment von {application} erfolgt in folgenden Schritten:

1. Voraussetzungen

- *Docker* ist installiert.
- Die Dateien aus dem *Konfigurationspaket* befinden sich im Arbeitsverzeichnis.
- (optional) Eine Proxy-Konfiguration ist vorbereitet.

2. Konfigurationsdaten

- Ermittlung und Übernahme der erforderlichen Daten (SharePoint-Anbindung, Authentifizierung, LLM Provider) in die `init_config.yaml` (siehe "Erstkonfiguration der Anwendung")

3. Login in Docker Hub Repository
  
- Nutzen Sie das bereitgestellte Read-Access-Token: `docker login -u cgsmbh [ACCESS_TOKEN]`

4. Starten der Anwendung 

- Anwendung starten: `docker compose up -d`
- Health Check abwarten

5. Abschluss

- Testen Sie die Erreichbarkeit der Webapplikation im Browser

==== Update-Prozess

Der Update-Prozess, durchgeführt vom Kunden, gestaltet sich wie folgt:

Empfehlung: Vor jedem Update sind vollständige Backups der Konfiguration und der Datenbank zu erstellen (`SHARED_FOLDER`).

- Stoppen Sie die Applikation: `docker compose down`
- Führen sie Updates der Konfiguration durch, falls notwendig (siehe "Deployment-Anleitung (Schritt-für-Schritt)"
- Laden Sie die neuen Images der Applikation von Docker Hub: `docker compose pull`
-- hierzu ist ggf. ein Login bei Docker Hub notwendig
- Starten Sie die Anwendung neu: `docker compose up -d`
- Prüfen Sie die korrekte Funktion

