
=== Allgemeine Informationen zur Applikation

==== Name und Version der Applikation

Die in diesem Handbuch beschriebene Anwendung trägt den Namen {application} und liegt in der aktuellen Version {revnumber} vom {revdate} vor. +
Dieses Dokument richtet sich an IT-Infrastruktur und Systemadministratoren und beschreibt die technischen Voraussetzungen für die Bereitstellung 
und den Betrieb der {application} Plattform beim Kunden.


==== Übersicht und Funktionen

{application} ist eine browserbasierte Webanwendung, die lokal beim Kunden gehostet wird. 
Der Betrieb erfolgt in Docker-Containern auf einem Linux-Server (entweder on-premise oder in einer Cloud-VM). 

Die Anwendung dient zur Nutzung von KI-Sprachmodellen (Large Language Models, LLMs), welche über eine externe API angebunden werden, u. a. Azure OpenAI. +
Mit {application} können Benutzer u.a.

* Dokumente analysieren
* Abfragen an KI‑Modelle stellen
* Daten verarbeiten
* Informationen kontextbezogen aufbereiten

{application} wird ohne eigene(s) KI-Sprachmodell(e) ausgeliefert. Stattdessen greift das Tool über eine API-Anbindung auf 
die LLM-Infrastruktur des Kunden zurück. Damit {application} ein Sprachmodell nutzen kann, muss eine funktionsfähige Anbindung 
an ein unterstütztes LLM eingerichtet werden.

==== Systemkomponenten 

Die Lösung besteht aus folgenden Komponenten:

* *Web-/API-Server:* {application} Backend, LLM API, RAG API, Caddy
* *Worker:* Celery-Worker für asynchrone Tasks
* *Redis:* Message-Broker und Caching
* *Datenbank:* SQLite
* *Vector-Store:* ChromaDB für RAG
* *optional kundenspezifische MCP APIs/Agents:* zum Austausch mit externen Tools, Systemen oder Datenquellen z.B. Feeds

*Deployment:* Über Docker auf Linux-Server.

===== Agents und MCP

KI Agents sind spezialisierte Software-Komponenten, die eigenständig komplexe Aufgaben automatisieren. 
Über einen MCP (Model Context Protocol) Server erhalten diese Agents sicheren und strukturierten Zugriff auf verschiedenste Datenbanken und Subsysteme, 
wie beispielsweise ERP-Systeme. +
Die Agents können:

* Daten abfragen oder analysieren
* relevante Informationen extrahieren
* Ergebnisse zentralisiert bereitstellen
* Prozesse automatisiert steuern

Dies ermöglicht u. a. automatisierte Berichte, dynamische Auswertungen oder Prozessautomatisierungen — ohne manuelle Eingriffe und über Systemgrenzen hinweg.

Weitere Anwendungsbeispiele:

- öffentliche Feeds auslesen und automatisiert innerhalb von {application} zur Verfügung stellen
- eingehendes E-Mails kategorisieren, inkl. Anhängen bewerten und priorisieren und zur Verfügung stellen
