
===== Registrierungsschritte im Microsoft Entra Admin Center

*Anmeldung*

Melden Sie sich im Microsoft Entra Admin Center mit einem Konto an, das über Administratorrechte für Ihre Organisation verfügt.
`https://entra.microsoft.com`

*Navigation zu "App-Registrierungen"*

* Wählen Sie ganz links Entra ID
* Navigieren Sie zu "App-Registrierungen".
* Neue Anwendung registrieren
* Klicken Sie auf "Neue Registrierung" (oben im Menü).

*Anwendungsinformationen eingeben*

* Name: Wählen Sie einen Namen für die Anwendung. *Vorschlag:* {application}
* Unterstützte Kontotypen: Entscheiden Sie, ob die Anwendung nur interne Benutzer (nur eigene Organisation), externe Benutzer oder 
mehrere Organisationen unterstützen soll. Standard eingestellt ist "Nur mein Mandant". 
* Umleitungs-URIs: *muss* eingetragen werden (url zur Weiterleitung auf {application}, entspricht der 'redirect_uri' in der `init_config.yaml`
*Hinweis*: Für {application} Sharepoint Anbindung ist die Einstellung nicht relevant.
** Für OpenID Connect zusätzlich die Auswahl "Web" und dort Eintrag "nur Unternehmen user" übernehmen

*Erstellen*

* Klicken Sie auf "Registrieren".
* Nach der Registrierung erhalten Sie:

** Anwendungs-ID *(Client-ID)*
** Verzeichnis-ID *(Tenant-ID)*
** *Client-Secrets* unter "Zertifikate & Geheimnisse" generieren
```
Hinweis: Notieren/Kopieren Sie sich die Werte für Ihre Anwendungskonfiguration `init_config.yaml`.
```