
==== OpenID Connect Authentifizierung mit Microsoft Entra ID

Die OpenID-Authentifizierung mit Microsoft Entra ID wird für alle professionellen, cloud- und unternehmensorientierten Anwendungen empfohlen, 
um Sicherheit, Nutzerkomfort und Compliance-Anforderungen adäquat adressieren zu können. Vorteil dieser Anmeldeform ist SSO (Single Sign-On)
d.h. Benutzer können sich mit ihren Unternehmensanmeldedaten (z. B. E-Mail/Passwort bei Microsoft 365) in verschiedensten Anwendungen anmelden.

Die notwendigen Daten, für die Anbindung von {application} mit OpenID Connect Authentifizierung des Kunden sind:

* *Tenant-ID:* Die ID der Organisation/Mandenten.
* *Anwendungs-ID (Client):* Die Client-ID der Anwendung.
* *Secrets:* Zugangsschlüssels (kann zeitlich begrenzt werden)
* *Redirect-URL:* Mmleitung nach erfolgreicher Anmeldeung zu {application}

Diese werden müssen in der `init_config.yaml` hinterlegt werden (siehe "Erstkonfiguration der Anwendung"). 
Diese Daten entsprechen denen in der Einrichtung "Sharepoint Anbindung über die Microsoft Entra ID" oder "SAML-Authentifizierung mit Microsoft Entra ID".

Sind diese Daten *nicht* vorhanden, muss die Applikation {application} vom Kunden erst in Microsoft Entra Admin Center registriert werden.
  
ifeval::[{big-output} == 2]

include::chapter2-5-2-auth-openid-o.adoc[]

endif::[]

