
=== Allgemeine Informationen zur Applikation

==== Name und Version der Applikation

Die in diesem Handbuch beschriebene Anwendung trägt den Namen {application} und liegt in der aktuellen Version {revnumber} vom {revdate} vor.

==== Übersicht und Funktionen

{application} ist eine browserbasierte Webanwendung, die lokal beim Kunden gehostet wird. 
Der Betrieb erfolgt in Docker-Containern auf einem Linux-Server (entweder on-premise oder in einer Cloud-VM). 
Die Anwendung dient zur Nutzung von KI-Sprachmodellen (Large Language Models, LLMs), welche über eine externe API angebunden werden, u. a. Azure OpenAI. 

Mit {application} können Nutzer effizient Dokumente analysieren, Abfragen stellen und Daten verarbeiten, basierend auf KI-Technologien.

{application} wird ohne eigene(s) KI-Sprachmodell(e) ausgeliefert. Stattdessen greift das Tool über eine API-Anbindung auf 
die LLM-Infrastruktur des Kunden zurück. Damit {application} ein Sprachmodell nutzen kann, muss eine funktionsfähige Anbindung 
an ein unterstütztes LLM eingerichtet werden.

==== Systemkomponenten 

Die Lösung besteht aus folgenden Komponenten:

* *Web-/API-Server:* AI Audit Assist Backend, LLM API, RAG API, Caddy
* *Worker:* Celery-Worker für asynchrone Tasks
* *Redis:* Message-Broker und Caching
* *Datenbank:* SQLite
* *Vector-Store:* ChromaDB für RAG
* *Kundenspezifische MCP APIs:* zum Austausch mit externen Tools, Systemen oder Datenquellen z.B. Feeds (optional)

*Deployment:* Über Docker auf Linux-Server.

==== Optionale kundenspezifische Implementierungen bzw.Erweiterungen

===== Agents und MCP

KI Agents sind spezialisierte Software-Komponenten, die eigenständig komplexe Aufgaben automatisieren. 
Über einen MCP (Model Context Protocol) Server erhalten diese Agents sicheren und strukturierten Zugriff auf verschiedenste Datenbanken und Subsysteme, 
wie beispielsweise ERP-Systeme. Sie können dort eigenständig Datenabfragen oder Analysen durchführen, relevante Informationen extrahieren, 
verarbeiten und die Ergebnisse in einem zentralen, einheitlichen Format bereitstellen. Auf diese Weise ermöglichen KI Agents automatisierte 
Berichte, dynamische Auswertungen oder die Steuerung von Prozessen – und das über Systemgrenzen hinweg, ohne dass manuelle Eingriffe notwendig sind.

Weitere Anwendungsbeispiele:

- öffentliche Feeds ausgelesen und automatisiert innerhalb von {application} zur Verfügung stellen
- eingehendes E-Mails kategorisieren, inkl. Anhängen bewerten und priorisieren

==== Begriffsdefinitionen und Abkürzungen

Im Folgenden werden zentrale Begriffe und Abkürzungen aufgeführt, die in diesem Handbuch verwendet werden:

- Applikation {application}: Die in diesem Handbuch behandelte KI-Plattform für den Mittelstand
- Admin: IT-Administrator mit erweiterten Zugriffsrechten auf die Anwendung und zugehörige Systeme
- User: Allgemeiner Benutzer der Anwendung mit eingeschränkten Rechten
- Backup: Datensicherung zur Wiederherstellung im Fall eines Ausfalls oder Datenverlusts
- Restore: Wiederherstellung von gesicherten Daten.
- DMS: Dokumenten Management System ist eine hi­e­r­ar­chische Dokumentenablage
- API: Application Programming Interface ist Programmierschnittstelle zur Integration mit anderen Systemen.
- LLM : Large Language Models sind Sprachmodelle zur Textgenerierung
- RAG : Retrieval-Augmented Generation ist ein Softwaresystem das Informationen aus LLM "aufbereitet" und Anworten generiert
- MCP : Model Context Protocol ist ein Open-Source-Standard zur Verbindung von KI-Anwendungen mit externen Systemen
