
==== Sharepoint Anbindung über die Microsoft Entra ID 

Die Anbindung von Sharepoint muss über eine API mit den Kundendaten erfolgen. 
In SharePoint werden einzelne Bereiche als Sites bezeichnet. Wenn z.B. eine neue Gruppe in MS Teams erstellt wird, erstellt SharePoint 
automatisch eine entsprechende SharePoint-Site, die mit dieser Gruppe verknüpft ist.

Die notwendigen Daten, für die Anbindung von {application} mit Credentials an Sharepoint des Kunden sind:

* *Tenant-ID:* Die ID der Organisation/Mandenten.
* *Anwendungs-ID (Client):* Die Client-ID der Anwendung.
* *Secrets:* Zugangsschlüssels (kann zeitlich begrenzt werden)

Diese werden in `initial.config` hinterlegt (siehe "Erstkonfiguration der Anwendung"). 
Diese Daten entsprechen denen in der Einrichtung "OpenID Connect Authentifizierung mit Microsoft Entra ID" oder "SAML-Authentifizierung mit Microsoft Entra ID"
Sind diese Daten nicht vorhanden, muss die Applikation {application} vom Kunden erst in Microsoft Entra Admin Center registriert werden.

ifeval::[{big-output} == 2]

include::chapter2-4-1-rag-sharepoint-o1.adoc[]

endif::[]

ifeval::[{big-output} == 2]

include::chapter2-4-1-rag-sharepoint-o2.adoc[]

endif::[]