
==== OpenID Connect Authentifizierung mit Microsoft Entra ID

Die OpenID Connect Authentifizierung mit Microsoft Entra ID wird für alle professionellen, cloud- und unternehmensorientierten Anwendungen empfohlen, 
um Sicherheit, Nutzerkomfort und Compliance-Anforderungen adäquat adressieren zu können. Vorteil dieser Anmeldeform ist SSO (Single Sign-On)
d.h. Benutzer können sich mit ihren Unternehmensanmeldedaten (z. B. E-Mail/Passwort bei Microsoft 365) in verschiedensten Anwendungen anmelden.

Die notwendigen Daten, für die Anbindung von {application} mit OpenID Connect Authentifizierung des Kunden sind:

* *Anwendungs-ID:* Die Client-ID der Anwendung.
* *Tenant-ID:* Die ID der Organisation/Mandenten.
* *Client-Secrets* geheimer Clientschlüssel, kann zeitlich begrenzt werden
* *Redirect‑URI:* Umleitung nach erfolgreicher Anmeldung zu {application}

Diese Angaben müssen in der `init_config.yaml` hinterlegt werden (siehe "Erstkonfiguration der Anwendung"). 

Sind diese Daten *nicht* vorhanden, muss die Applikation {application} vom Kunden erst über das 
Microsoft Entra Admin Center registriert werden.  


