
==== SAML-Authentifizierung mit Microsoft Entra ID

Die SAML-Authentifizierung mit Microsoft Entra ID ist immer dann erforderlich, wenn moderne Single Sign-On-Funktionalität 
und zentrale Identitätsverwaltung für Anwendungen genutzt werden sollen, die auf SAML (Security Assertion Markup Language) statt OpenID Connect setzen – 
und ergänzt so optimal das gesamte Identitäts- und Sicherheitskonzept eines Unternehmens.
Die SAML-Authentifizierung mit Microsoft Entra ID ermöglicht es, Anwendungen, speziell ältere oder spezialisierte Systeme, 
zentral und sicher an das Identitätsmanagement von Microsoft anzubinden.

Die notwendigen Daten, für die Anbindung von {application} mit SAML-Authentifizierung des Kunden sind:

* *Verzeichnis-ID (Mandant):* Die Tenant ID der Organisation/Mandenten (unter Übersicht).
* *Anwendungs-ID (Client):* Die Client-ID der Anwendung (unter Übersicht).
* *Client-Secrets*: der geheime Clientschlüssel, kann zeitlich begrenzt werden (unter Zertifikate & Geheimnisse).
* *Redirect‑URI* Umleitung nach erfolgreicher Anmeldung zu {application} (unter Übersicht).

Diese Angaben müssen in der `init_config.yaml` hinterlegt werden (siehe "Erstkonfiguration der Anwendung"). 

Sind diese Daten *nicht* vorhanden, muss die Applikation {application} vom Kunden erst über das 
Microsoft Entra Admin Center registriert werden.