
==== OpenID Connect Authentifizierung mit Microsoft Entra ID

OpenID Connect mit Microsoft Entra ID bietet sich für alle professionellen Cloud‑ und Business‑Anwendungen an, da es sicheres Single Sign‑On mit Unternehmensanmeldedaten und zentrale Identitäts‑ und Compliance‑Funktionen bereitstellt.

Die notwendigen Daten, für die Anbindung von {application} mit OpenID Connect Authentifizierung des Kunden sind:

* *Verzeichnis-ID (Mandant):* Die Tenant ID der Organisation/Mandenten (unter Übersicht).
* *Anwendungs-ID (Client):* Die Client-ID der Anwendung (unter Übersicht).
* *Client-Secrets*: der geheime Clientschlüssel, kann zeitlich begrenzt werden (unter Zertifikate & Geheimnisse).
* *Redirect‑URI* Umleitung nach erfolgreicher Anmeldung zu {application} (unter Übersicht).

Diese Angaben müssen in der `init_config.yaml` hinterlegt werden (siehe "Erstkonfiguration der Anwendung"). 

Sind diese Daten *nicht* vorhanden, muss die Applikation {application} vom Kunden erst über das 
Microsoft Entra Admin Center registriert werden.  


