
==== E-Mail Integration mit Microsoft Entra ID 

Die E-Mail Integration muss über eine API mit den Kundendaten erfolgen. Microsoft Graph ist die zentrale API, 
um auf Dienste in Microsoft 365 zuzugreifen – z. B. Outlook‑Mails, Kalender, OneDrive, Teams usw.
Damit eine Anwendung über die Graph‑API auf Benutzerdaten wie E-Mails zugreifen darf, muss Microsoft sicherstellen, dass:

* die Identität des Benutzers oder der App bekannt ist
* die nötigen Berechtigungen erteilt wurden.

Dafür ist Microsoft Entra ID zuständig.

Die notwendigen Daten, für die Integration von {application} und Mail(Microsoft 365 / Graph) des Kunden sind:

* *Verzeichnis-ID (Mandant):* Die Tenant ID der Organisation/Mandenten (unter Übersicht).
* *Anwendungs-ID (Client):* Die Client-ID der Anwendung (unter Übersicht).
* *Redirect‑URI* Umleitung nach erfolgreicher Anmeldung zu {application} (unter Übersicht).
* *Client-Secrets Value*: Wert des geheimen Clientschlüssel, kann zeitlich begrenzt werden (unter Zertifikate & Geheimnisse).
* *Client Secret ID*: Id des geheimen Clientschlüssel (unter Zertifikate & Geheimnisse).
* *Object ID*: der eindeutige, unveränderliche technische Identifikator der App-Registrierung (unter Übersicht).

Diese Angaben müssen in der `init_config.yaml` hinterlegt werden (siehe "Erstkonfiguration der Anwendung"). 

Sind diese Daten *nicht* vorhanden, muss die Applikation {application} vom Kunden erst über das 
Microsoft Entra Admin Center registriert werden.
