
==== SAML-Authentifizierung mit Microsoft Entra ID

Die SAML‑Authentifizierung mit Microsoft Entra ID ermöglicht es, speziell ältere oder SAML‑basierte Anwendungen sicher in ein zentrales Single‑Sign‑On‑ und Identitätsmanagement einzubinden und so nahtlos in das unternehmensweite Sicherheits‑ und Identitätskonzept zu integrieren.

Die notwendigen Daten, für die Anbindung von {application} mit SAML-Authentifizierung des Kunden sind:

* *Verzeichnis-ID (Mandant):* Die Tenant ID der Organisation/Mandenten (unter Übersicht).
* *Anwendungs-ID (Client):* Die Client-ID der Anwendung (unter Übersicht).
* *Client-Secrets*: der geheime Clientschlüssel, kann zeitlich begrenzt werden (unter Zertifikate & Geheimnisse).
* *Redirect‑URI* Umleitung nach erfolgreicher Anmeldung zu {application} (unter Übersicht).

Diese Angaben müssen in der `init_config.yaml` hinterlegt werden (siehe "Erstkonfiguration der Anwendung"). 

Sind diese Daten *nicht* vorhanden, muss die Applikation {application} vom Kunden erst über das 
Microsoft Entra Admin Center registriert werden.

[.highlight]#*Hinweis*: Diese Form der Authentifizierung wird von {application} vollständig unterstützt. Alternative oder erweiterte Forme sind ebenfalls möglich, fallen jedoch nicht unter den Standardumfang und werden separat angeboten.#