===== Registrierungsschritte in Microsoft Entra ID ID Admin Center

*Anmeldung*

Melden Sie sich im Microsoft Entra ID Admin Center mit einem Konto an, das über Administratorrechte für Ihre Organisation verfügt.
`https://entra.microsoft.com`

*Navigation zu "App-Registrierungen"*

* Wählen Sie Entra ID
* Navigieren Sie zu "App-Registrierungen".
* Neue Anwendung registrieren
* Klicken Sie auf "Neue Registrierung" (oben im Menü).

*Anwendungsinformationen eingeben*

* Name: Wählen Sie einen Namen für die Anwendung. *Vorschlag:* {application}
* Unterstützte Kontotypen: Entscheiden Sie, ob die Anwendung nur interne Benutzer (nur eigene Organisation), externe Benutzer oder 
mehrere Organisationen unterstützen soll. Standard eingestellt ist "Nur ein Mandant - CGS mbH". 
* Redirect-URL: muss eingetragen werden (url zur Weiterleitung auf {application}, entspricht der 'redirect_uri' in der `init_config.yaml`
** Auswahl "Web"
** Eintrag "nur Unternehmen user" übernehmen

*Erstellen*

* Klicken Sie auf "Registrieren".
* Nach der Registrierung erhalten Sie:

** Anwendungs-ID *(Client-ID)*
** Verzeichnis-ID *(Tenant-ID)*
** *Client-Secrets* unter "Zertifikate & Geheimnisse" generieren
```
Hinweis: Notieren/Kopieren Sie sich die Werte für Ihre Anwendungskonfiguration `init_config.yaml`.
```
====== SAML-Basisdaten in Entra ID konfigurieren

Unter *Einmaliges Anmelden (Single Sign-On)" > muss auf SML umgeschaltet werden.

*Grundlegende SAML-Konfiguration*

* *Bezeichner (Entity ID)*: Die eindeutige Kennung im Admin Center.
* *Antwort-URL*: Anwendungs-Url, muss identisch der Angabe "redirect_uri" in der `init_config.yaml` sein.

*Attribute & Ansprüche*

Diese Daten müssen angelegt werden, damit bei jeder Anmeldung die Benutzerdaten in die Applickation {application} gespiegelt werden können.
Damit wird sichergestellt das die Applikation immer die neuesten Bnutzerdaten (Vorname, Nachname, EMail) enthält.






