===== Registrierungsschritte in Microsoft Entra ID ID Admin Center

*Anmeldung*

Melden Sie sich im Microsoft Entra ID Admin Center mit einem Konto an, das über Administratorrechte für Ihre Organisation verfügt.
`https://entra.microsoft.com`

*Navigation zu "App-Registrierungen"*

* Wählen Sie Entra ID
* Navigieren Sie zu "App-Registrierungen".
* Neue Anwendung registrieren
* Klicken Sie auf "Neue Registrierung" (oben im Menü).

*Anwendungsinformationen eingeben*

* Name: Wählen Sie einen Namen für die Anwendung. *Vorschlag:* {application}
* Unterstützte Kontotypen: Entscheiden Sie, ob die Anwendung nur interne Benutzer (nur eigene Organisation), externe Benutzer oder 
mehrere Organisationen unterstützen soll. Standard eingestellt ist "Nur ein Mandant - CGS mbH". 
*Hinweis*: Für {application} Sharepoint Anbindung ist die Einstellung nicht relevant.

*Erstellen*

* Klicken Sie auf "Registrieren".
* Nach der Registrierung erhalten Sie:

** Anwendungs-ID *(Client-ID)*
** Verzeichnis-ID *(Tenant-ID)*
** *Client-Secrets* unter "Zertifikate & Geheimnisse" generieren
```
Hinweis: Notieren/Kopieren Sie sich die Werte für Ihre Anwendungskonfiguration `init_config.yaml`.
```
*Berechtigungen konfigurieren (optional)*

* Unter "API-Berechtigungen" können die Berechtigungen für den Zugriff auf SharePoint-Sites mit Hilfe der Graph API verwaltet werden.

