
==== SAML-Authentifizierung mit Microsoft Entra ID

Die SAML-Authentifizierung mit Microsoft Entra ID ist immer dann erforderlich, wenn moderne Single Sign-On-Funktionalität 
und zentrale Identitätsverwaltung für Anwendungen genutzt werden sollen, die auf SAML (Security Assertion Markup Language) statt OpenID Connect setzen – 
und ergänzt so optimal das gesamte Identitäts- und Sicherheitskonzept eines Unternehmens.
Die SAML-Authentifizierung mit Microsoft Entra ID ermöglicht es, Anwendungen, speziell ältere oder spezialisierte Systeme, 
zentral und sicher an das Identitätsmanagement von Microsoft anzubinden.

*Vorteile und Nutzen*

* *Single Sign-On (SSO):*
  Nutzer melden sich mit ihren gewohnten Unternehmensdaten bei verschiedensten (auch externen oder Drittanbieter-) Anwendungen an.
* *Integration von Legacy-Anwendungen:*
  SAML ist ein etablierter Standard, den viele bestehende on-premises oder SaaS-Anwendungen unterstützen.
* *Zentrale Identitäts- und Zugriffsverwaltung:*
  Benutzer, Gruppen und Rechte werden in Microsoft Entra ID gepflegt und können für alle SAML-angebundenen Systeme gelten.
* *Multi-Faktor-Authentifizierung (MFA):*
  Moderne Security-Policies und Zusatz-Authentifizierungsmethoden wie MFA stehen auch SAML-Apps zur Verfügung.
* *Transparenz und Kontrolle:*
  Zugriffe, Anmeldungen und Policy-Verstöße sind zentral auditierbar.

*Notwendigkeit*

* *Bestandssysteme:* Viele in Unternehmen etablierte (Business-)Anwendungen unterstützen ausschließlich SAML als Authentifizierungsmethode.
* *Kompatibilität:* SAML ermöglicht die Integration von Microsoft-Entra-Identity mit Drittsystemen, Portalen oder Spezialsoftware, 
die kein modernes Protokoll wie OpenID Connect unterstützen.
* *Sicheres Zentrales Authentifizierungsverfahren:* Benutzerverwaltung, Passwortmanagement und Compliance-Auflagen werden zentral bündelt und gesteuert.

===== Voraussetzungen

* Ein Microsoft Entra ID Mandant und Zugriff auf das Microsoft Entra Admin Center: https://entra.microsoft.com
* Eine als „Unternehmensanwendung“ (*Enterprise Application*) registrierte Applikation (siehe "Registrierung einer Anwendung im Microsoft Entra ID Admin Center")
* Unterstützung von SAML 2.0 in der Zielanwendung ({application})
* Zugriff auf die SAML-Metadaten oder Konfigurationsendpunkte des Service Providers (SP)

ifeval::[{big-output} == 2]

include::chapter2-5-1-auth-saml-o.adoc[]

endif::[]

