
=== RAG

==== Integriertes "Dokumentenmanagementsystem"

Das ist eine SQLight DB Anbindung in der systemseitig festgelegte Ordner und vom Kunden leicht zu pflegende Dokumente gespeichert sind. 

==== Sharepoint Andindung über Microsoft Entra ID gesicherte API

Die Anbindung von Sharepoint muss über Microsoft Entra ID durch den Kunden erfolgen. 
In SharePoint werden einzelne Bereiche Sites genannt. Wenn eine Gruppe in teams erstellt wird, erstellt SharePoint 
automatisch eine entsprechende SharePoint-Site, die mit der Gruppe verknüpft ist.
Aufruf des Listing z.B https://kunde.sharepoint.com/sites/

Die notwendigen Daten, für die Anbindung von {application} an Sharepoint des Kunden sind:

* Tenant ID: Die ID des SharePoint-Mandanten, normalerweise eine GUID.
* Application ID: Die Client-ID der SharePoint-Anwendung mit den erforderlichen Berechtigungen (ClientSecrets) für den Datenzugriff.
* ClientSecrets: Die SharePoint-Application-Berechtigungen für den Datenzugriff.

Diese werden in einen config file hinterlegt (siehe "Erstkonfiguration der Anwendung")
Sind diese Daten nicht vorhanden muss die Client Applikation {aplication} in Microsoft Entra ID auf Mandant Kunde "https://kunde.sharepoint.com/sites/" registriert werden.

*Registrieren einer Anwendung in Microsoft Entra ID:*

https://learn.microsoft.com/de-de/entra/identity-platform/quickstart-register-app


