
===== Applikation registrieren im Microsoft Entra Admin Center für SAML

*Anmeldung*

Melden Sie sich im Microsoft Entra Admin Center mit einem Konto an, das über Administratorrechte für Ihre Organisation verfügt.
`https://entra.microsoft.com`

*Navigation zu "App-Registrierungen"*

* Wählen Sie ganz links Entra ID
* Navigieren Sie zu "App-Registrierungen".
* Neue Anwendung registrieren
* Klicken Sie auf "Neue Registrierung" (oben im Menü).

*Anwendungsinformationen eingeben*

* Name: Wählen Sie einen Namen für die Anwendung. Der Name ist später sichtbar. *Vorschlag:* {application}-client-app
* Unterstützte Kontotypen: Entscheiden Sie, ob die Anwendung nur interne Benutzer (nur eigene Organisation), externe Benutzer oder 
mehrere Organisationen unterstützen soll. Standard eingestellt ist "Nur mein Mandant". 
* Redirect‑URI:* muss identisch der Angabe "redirect_uri" in der `init_config.yaml` sein.

*Erstellen*

* Klicken Sie auf "Registrieren".

*SAML als Authentifizierungsmethode aktivieren*

* In der App linke Seite auf Single-Sign-On gehen
* SAML auswählen
* Es öffnet sich die Seite SAML‑basierte Konfiguration

*Grundlegende SAML-Konfiguration*

* *Bezeichner (Entity ID)*: Die eindeutige Kennung im Admin Center.
* *Redirect-URL*: muss identisch der Angabe "redirect_uri" in der `init_config.yaml` sein.

*Attribute & Claims*

Diese Daten müssen angelegt werden, damit bei jeder Anmeldung die Benutzerdaten in die Applickation {application} gespiegelt werden können.
Damit wird sichergestellt das die Applikation immer die neuesten Benutzerdaten (Vorname, Nachname, EMail) enthält.

*SAML Certificates*

Die dort angebotene "Federation Metadata XML" *muss* heruntergeladen und im SHARED_FOLDER *abgelegt* werden und identisch der Angabe "idp_metadata_path" in der `init_config.yaml` sein.

Die Datei enthält:

* Entity ID
* SSO URL
* Zertifikate zum Validieren der Signaturen

*Konfigurationsdaten:*

** Anwendungs-ID: *Client-ID*
** Mandant-ID: *Tenant-ID*
** geheimer Clientschlüssel: *Client-Secrets*, kann zeitlich begrenzt werden
** Redirect‑URI:* Umleitung nach erfolgreicher Anmeldung zu {application}
```
Hinweis: Notieren/Kopieren Sie sich die Werte für Ihre Anwendungskonfiguration `init_config.yaml`.
``` 








