
==== SAML-Authentifizierung mit Microsoft Entra ID

Die SAML-Authentifizierung mit Microsoft Entra ID ist immer dann erforderlich, wenn moderne Single Sign-On-Funktionalität 
und zentrale Identitätsverwaltung für Anwendungen genutzt werden sollen, die auf SAML (Security Assertion Markup Language) statt OpenID Connect setzen – 
und ergänzt so optimal das gesamte Identitäts- und Sicherheitskonzept eines Unternehmens.
Die SAML-Authentifizierung mit Microsoft Entra ID ermöglicht es, Anwendungen, speziell ältere oder spezialisierte Systeme, 
zentral und sicher an das Identitätsmanagement von Microsoft anzubinden.

Die notwendigen Daten, für die Anbindung von {application} mit SAML-Authentifizierung des Kunden sind:

* *Tenant-ID:* Die ID der Organisation/Mandenten.
* *Anwendungs-ID (Client):* Die Client-ID der Anwendung.
* *Secrets:* Zugangsschlüssels (kann zeitlich begrenzt werden)

Diese werden müssen in der `init_config.yaml` hinterlegt werden (siehe "Erstkonfiguration der Anwendung"). 
Diese Daten entsprechen denen in der Einrichtung "Sharepoint Anbindung über die Microsoft Entra ID" oder "OpenID Connect Authentifizierung mit Microsoft Entra ID"
Sind diese Daten *nicht* vorhanden, muss die Applikation {application} vom Kunden erst in Microsoft Entra Admin Center registriert werden.


ifeval::[{big-output} == 2]

include::chapter2-5-1-auth-saml-o.adoc[]

endif::[]

