
=== RAG

==== Integriertes "Dokumentenmanagementsystem"

Das ist eine SQLight DB Anbindung in der systemseitig festgelegte Ordner und vom Kunden leicht zu pflegende Dokumente gespeichert sind.
Die Ordner werden per Script nach Kundenwunsch in der DB erzeugt. Diese sind für alle sichtbar. 
Die erforderlichen Berechtigungen der Rollen auf die Ordner setzt der Kunde selbst.

Die Dateien werden vom Kunden per hand hochgeladen. Es sind bis zu 10 Dateien gleichzeitig möglich.
Die Berechtigungen auf die einzelnen Dateien entsprechen denen der Verzeichnisse.

==== Sharepoint Andindung über Microsoft Entra ID gesicherte API

Die Anbindung von Sharepoint muss über Microsoft Entra ID durch den Kunden erfolgen. 
In SharePoint werden einzelne Bereiche als Sites bezeichnet. Wenn eine Gruppe in MS Teams erstellt wird, erstellt SharePoint 
automatisch eine entsprechende SharePoint-Site, die mit der Gruppe verknüpft ist.
Aufruf des Listing z.B https://kunde.sharepoint.com/sites/

Die notwendigen Daten, für die Anbindung von {application} an Sharepoint des Kunden sind:

* **Tenant-ID:** Die ID des SharePoint-Mandanten, normalerweise eine GUID.
* **Client-ID:** Die Client-ID der SharePoint-Anwendung mit den erforderlichen Berechtigungen (ClientSecrets) für den Datenzugriff.
* **ClientSecrets:** Die SharePoint-Application-Berechtigungen für den Datenzugriff.

Diese werden in einen config file hinterlegt (siehe "Erstkonfiguration der Anwendung")
Sind diese Daten nicht vorhanden muss die Client Applikation {aplication} in Microsoft Entra ID unter https://kunde.sharepoint.com/sites/ registriert werden.

ifeval::[{big-output} == 1]

===== Registrierung einer Anwendung in Microsoft Entra ID

Dies ist der erste Schritt, wenn eine Applikation die Microsoft Identitätsdienste (z. B. Anmeldung mit Microsoft-Konto, Zugriff auf APIs) verwendet.
Nach der Registrierung kann {application} App Microsoft-Identitätsplattform-Funktionen verwenden (z. B. Anmeldung, Zugriff auf Graph-API usw.).

Wichtige Schritte:

* Anmelden beim Azure-Portal
** Melden Sie sich mit Ihrem Konto und Administratorberechrigungen beim Azure-Portal an. Dort haben sie die Tenant-ID.

* App-Registrierungen öffnen
** Navigieren Sie im Menü zu Microsoft Entra ID und wählen Sie dort App-Registrierungen aus.

* Neue Registrierung erstellen
** Klicken Sie auf Neue Registrierung und geben Sie folgende Details an:
*** Name der Anwendung
*** Unterstützte Kontotypen (wer sich bei der App anmelden darf)
*** Umleitungs-URI (optional, für Web-/Mobile-Apps)

* Registrierung abschließen
** Klicken Sie auf Registrieren. Danach erhalten Sie eine Anwendungs-ID (Client-ID), mit der Sie die App eindeutig identifizieren können.

* Weitere Einstellungen
** Optional können Sie API-Berechtigungen konfigurieren (ClientSecrets), Zertifikate hinzufügen usw., je nach Bedarf der Anwendung.

endif::[]
