

name: Asciidoctor Build DIFFERENCES de

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      pdfTheme:
        description: 'Asciidoctor PDF Theme'
        required: true
        default: 'CGS'
        type: choice
        options:
          - CGS
          - ARC
      outputType:
        description: 'Asciidoctor Output type'
        required: true
        default: '0'
        type: choice
        options:
          - 0
          - 1
      version:
        description: 'Asciidoctor PDF Version'
        required: true
        default: '1.0.0'
        type: string
      application:
        description: 'Asciidoctor PDF Application name'
        required: true
        default: 'CGS Assist'
        type: choice
        options:
          - CGS Assist
          - AI Audit Assist
      author:
        description: 'Asciidoctor PDF author'
        required: true
        default: 'CGS Software and Data'
        type: choice
        options:
          - CGS Software and Data
          - AI Audit Institut
          

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files to check if documentation/sales_manuals/index.adoc exists
        run: ls -l documentation/sales_manuals/

      - name: Run asciidoctor on index.adoc
        run: asciidoctor documentation/sales_manuals/index.adoc

  pages:
    runs-on: ubuntu-latest
    container:
      image: asciidoctor/docker-asciidoctor:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build HTML and PDF docs
        run: |
          asciidoctor \
          -D documentation/sales_manuals/ \
          -a revnumber=${{ github.event.inputs.version }} \
          -a big-output=${{ github.event.inputs.outputType }} \
          -a application="${{ github.event.inputs.application }}" \
          -a author="${{ github.event.inputs.author }}" \
          -o DIFFERENCES_DE_Typ_${{ github.event.inputs.outputType }}_Version_${{ github.event.inputs.version }}.html documentation/sales_manuals/index.adoc
          asciidoctor-pdf \
          -D documentation/sales_manuals/ \
          -a revnumber=${{ github.event.inputs.version }} \
          -a big-output=${{ github.event.inputs.outputType }}  \
          -a application="${{ github.event.inputs.application }}" \
          -a author="${{ github.event.inputs.author }}" \
          -a pdf-theme=${{ github.event.inputs.pdfTheme }} \
          -a pdf-themesdir=documentation/sales_manuals/themes \
          -o DIFFERENCES_DE_Typ_${{ github.event.inputs.outputType }}_Version_${{ github.event.inputs.version }}.pdf documentation/sales_manuals/index.adoc

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: DIFFERENCES_DE_${{ github.event.inputs.outputType }}
          path: |
            documentation/sales_manuals/DIFFERENCES_DE_*.pdf
            documentation/sales_manuals/DIFFERENCES_DE_*.html
