name: Build Comparison de to html, pdf, docx

name: Build Catalog

on:
  workflow_dispatch:
    inputs:
      UC1:
        description: "Grundsatz"
        required: false
        type: boolean
      UC2:
        description: "Durchführung des Prüfungsengagements"
        required: false
        type: boolean
      UC3:
        description: "CGS Intern"
        required: false
        type: boolean
        
 env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  FILENAME: 'USE_CASE_CATALOG_DE'
  FILEPATH: 'usesCasesCatalog/de'
        
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Asciidoctor & Asciidoctor-pdf
        run: |
          sudo gem install asciidoctor asciidoctor-pdf

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.6.2'
          
      - name: Build PDF with Asciidoctor-pdf
        run: |
          asciidoctor-pdf \
           -D ${{ env.FILEPATH}}/ \
           -a UC1="${{ github.event.inputs.UC1 }}" \
           -a UC2="${{ github.event.inputs.UC2 }}" \
           -a UC3="${{ github.event.inputs.UC3 }}" \
           -a application="CGS Assist: Software für den Mittelstand - Uses Case Katalog"" \
           -a pdf-theme="CGS" \
           -a pdf-themesdir=./themes \
           -o ${{ env.FILENAME }}.pdf ${{ env.FILEPATH}}/index.adoc

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILENAME }}
          path: |
            ${{ env.FILEPATH}}/${{ env.FILENAME }}*.pdf

