name: Build Catalog

on:
  workflow_dispatch:
    inputs:
      UC1:  { type: boolean, required: false, default: false, description: "UC1" }
      UC2:  { type: boolean, required: false, default: false, description: "UC2" }
      UC3:  { type: boolean, required: false, default: false, description: "UC3" }
      UC4:  { type: boolean, required: false, default: false, description: "UC4" }

        
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  FILENAME: 'USE_CASE_CATALOG_DE'
  FILEPATH: 'usesCasesCatalog/de'
        
jobs:
  parse-json:
    runs-on: ubuntu-latest
    env:
      JSONPATH: usesCasesCatalog/de/usecases.json

    steps:
      # Repository auschecken (damit die JSON-Datei verfügbar ist)
      - name: Checkout
        uses: actions/checkout@v4

      # JSON sicher in einen Output schreiben (multiline delimiter)
      - name: Load JSON (multiline output)
        id: load_json_out
        shell: bash
        run: |
          echo "json<<__JSON__" >> "$GITHUB_OUTPUT"
          cat "$JSONPATH" >> "$GITHUB_OUTPUT"
          echo "__JSON__" >> "$GITHUB_OUTPUT"

      # Beispiel 1: Direkt in einer Expression (ohne Shell-Parsing) nutzen
      - name: Use first item via fromJSON (expression only)
        run: |
          echo "Name[0]: ${{ fromJSON(steps.load_json_out.outputs.json).UseCases[0].name }}"
          echo "Beschreibung[0]: ${{ fromJSON(steps.load_json_out.outputs.json).UseCases[0].description }}"


  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Asciidoctor & Asciidoctor-pdf
        run: |
          sudo gem install asciidoctor asciidoctor-pdf

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.9'
          
      - name: Install envsubst (gettext)
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Setze Werte in variablen
        run: |
          # Setze Auswahl dynamisch
          if [ "${{ github.event.inputs.UC1 }}" = true ]; then
            echo "UC1=1" >> $GITHUB_ENV
            # Nachfolger
            echo "UC3=1" >> $GITHUB_ENV
          else
            echo "UC1=0" >> $GITHUB_ENV
          fi
          # Setze Auswahl dynamisch
          if [ "${{ github.event.inputs.UC2 }}" = true ]; then
            # Vorgänger
            echo "UC1=1" >> $GITHUB_ENV
            echo "UC2=1" >> $GITHUB_ENV
          else
            echo "UC2=0" >> $GITHUB_ENV
          fi
          # Setze Auswahl dynamisch
          if [ "${{ github.event.inputs.UC3 }}" = true ]; then
            echo "UC3=1" >> $GITHUB_ENV
          else
            echo "UC3=0" >> $GITHUB_ENV
          fi

      - name: Read version from file
        id: read_version
        run: |
          VERSION=$(cat VERSION.txt)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          
      - name: Build PDF with Asciidoctor-pdf
        run: |
          asciidoctor-pdf \
           -D ${{ env.FILEPATH}}/ \
           -a UC1="${{ env.UC1 }}" \
           -a UC2="${{ env.UC2 }}" \
           -a UC3="${{ env.UC3 }}" \
           -a application="CGS Assist: Software für den Mittelstand - Uses Case Katalog" \
           -a pdf-theme="CGS" \
           -a pdf-themesdir=./themes \
           -o ${{ env.FILENAME }}_${{ env.VERSION }}.pdf ${{ env.FILEPATH}}/index.adoc

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILENAME }}_${{ env.VERSION }}
          path: |
            ${{ env.FILEPATH}}/${{ env.FILENAME }}*.pdf