
=== Anleitung zur Erstellung eines Anwendungsfalls

Diese Anleitung beschreibt Schritt für Schritt, wie Sie einen Standard-Anwendungsfall spezifizieren können. Ziel ist es, wiederkehrende Aufgaben effizienter zu gestalten, zu standardisieren und die Qualität der Ergebnisse zu verbessern. Dafür bietet der {application} unter „Anwendungsfälle“ verschiedene Standard-Anwendungsfälle (Kacheln) an.

Diese Anwendungsfälle bestehen immer aus einer Eingabeoberfläche (Formular), in welchem ein standardisierter Input über entsprechende Eingabefelder, Auswahlfelder oder Regler etc. eingegeben werden kann. Für das Ausfüllen der Eingabeoberfläche sind keinerlei KI-Kenntnisse nötig, sondern jeder Benutzer kann dies einfach ausfüllen. +
Im Hintergrund ist ein zentral festgelegter Standard Prompt hinterlegt. Nach dem Ausfüllen der Eingabeoberfläche werden die gemachten Eingaben in einem User Prompt durch den {application} übernommen, beide Prompts vereint und an das KI-System übergeben. +

Füllt zum Beispiel der Benutzer das Eingabefeld „Branche“ mit dem Inhalt _„Versicherung“_ aus, wird dies im User Prompt übernommen. Im standardisierten System Prompt wird inhaltlich z.B. nach _"Verträgen mit kurzen Vertragslaufzeiten"_ gefragt. Im vereinten Promt des {application} wird daraus dann im Context "Versicherung" angefragt. Der standardisierte System Prompt kann durch die Inhalte der Eingabeoberfläche (Formular) z.B. auch im Kontext "Stromanbieter" genutzt werden.
Damit bringen wir eine einfache Eingabe des Inputs mit einem zentralen Standardprompt zusammen und können unabhängig der KI-Kenntnisse des einzelnen Benutzers einen einheitlichen Qualitätsstandard erreichen.

Gerne implementieren wir für Sie individuelle Use Cases als Standard-Anwendungsfälle für Ihr Unternehmen. Erhalten wir die Spezifikation und Erläuterung Ihres Anwendungsfalls in der beschriebenen Form, ist in der Regel eine sehr kurzfristige Umsetzung möglich.
