"{author}" is the manufacturer of {application}, an AI wrapper that offers various functionalities to make AI
ifeval::[{cgs-assist} == 1]
 available, for example, to medium-sized enterprises
endif::[]
ifeval::[{arc-assist} == 1]
 for Internal Audit
endif::[]
 easier and better to use. Various LLMs from different providers can be integrated via the API, including OpenAI through Azure AI Foundry, 
 as well as other models via AWS Bedrock and even open source models that are self-hosted.
The application runs on the customer's premises (onPremise), so all data is stored within the customer's infrastructure.
Only the data required for the request is transmitted to the respective LLM for processing and may be temporarily cached for a short time if necessary.

{application} is a browser-based web application that is hosted locally at the customer's site.
Operation takes place in Docker containers on a Linux server (either on-premise or in a cloud VM).
The application is used to leverage AI language models (Large Language Models, LLMs), which are connected via an external API, such as Azure OpenAI.

With {application}, users can efficiently analyze documents, make queries, and process data based on AI technologies.

{application} is delivered without its own AI language model(s). Instead, the tool accesses the customer's LLM infrastructure via an API connection. 
In order for {application} to use a language model, a functional connection to a supported LLM must be set up.

==== Optional/Customer-Specific Implementations/Extensions

===== Agents and MCP

AI agents are specialized software components that independently automate complex tasks.
Through an MCP (Model Context Protocol) server, these agents are given secure and structured access to various databases and subsystems, such as ERP systems. 
They can autonomously perform data queries or analyses, extract and process relevant information, and provide the results in a central, uniform format. 
In this way, AI agents enable automated reports, dynamic analyses, or the control of processes—even across system boundaries, without the need for manual intervention.

Further use cases:

- Reading public feeds and making them automatically available within {application}
- Categorizing incoming emails, including evaluating and prioritizing attachments
