
==== E-Mail Integration with Microsoft Entra ID

E-mail integration must be implemented via an API using the customer’s data.  
Microsoft Graph is the central API for accessing Microsoft 365 services –  
e.g., Outlook mail, calendars, OneDrive, Teams, etc.

For an application to access user data such as e‑mails through the Graph API,  
Microsoft must ensure that:

* the identity of the user or application is known  
* the required permissions have been granted  

Microsoft Entra ID is responsible for this.

The necessary information for integrating {application} with Mail (Microsoft 365 / Graph) for the customer is:

* *Directory ID (Tenant):* The tenant ID of the organization (under Overview).  
* *Application ID (Client):* The client ID of the application (under Overview).  
* *Redirect URI:* Redirect target after successful login back to {application} (under Overview).  
* *Client Secret Value:* Value of the secret client key, can be time‑limited (under Certificates & secrets).  
* *Client Secret ID:* ID of the secret client key (under Certificates & secrets).  
* *Object ID:* The unique, immutable technical identifier of the app registration (under Overview).  

This information must be stored in the `init_config.yaml` file  
(see “Initial application configuration”).

If this information is *not* available, the customer must first register  
the application {application} in the Microsoft Entra Admin Center.
