
==== OpenID Connect Authentication with Microsoft Entra ID

OpenID Connect authentication with Microsoft Entra ID is recommended for all professional, cloud-based, and enterprise-oriented applications to adequately address security, user convenience, and compliance requirements. The advantage of this authentication method is SSO (Single Sign-On), meaning users can log in to various applications with their corporate credentials (e.g., email/password for Microsoft 365).

The necessary data for connecting {application} with the customer’s OpenID Connect authentication are:

* *Tenant-ID:* The ID of the organization/tenant.
* *Anwendungs-ID:* The client ID of the application.
* *Client-Secrets* Access keys (can be time-limited)
* *Redirect‑URI:* Redirect after successful login to {application}

These details must be stored in the init_config.yaml file (see ‘Initial configuration of the application’).

If this data is *not* available, the {application} must first be registered by the customer in the Microsoft Entra Admin Center.

 



