
==== SharePoint connection via the Microsoft Entra ID (formerly Azure Active Directory) secured API

The connection to SharePoint must be established via an API using customer-specific data.
In SharePoint, individual areas are referred to as sites. For example, when a new group is created in MS Teams, SharePoint 
automatically creates the corresponding SharePoint site linked to this group.

The necessary data for connecting {application} with credentials to the customer's SharePoint are:

* **Tenant ID:** The ID of the tenant, usually a GUID.
* **Client ID:** The client ID of the application with the necessary permissions (client secrets) for data access.
* **Client secrets:** The SharePoint application permissions required for data access.

These are stored in a configuration file (see "Initial configuration of the application"). If this data is not available, 
the application {application} must first be registered by the customer in the Microsoft Entra Admin Center.

ifeval::[{big-output} == 1]

include::chapter2-4-1-rag-sharepoint-o1.adoc[]

endif::[]

ifeval::[{big-output} == 1]

include::chapter2-4-1-rag-sharepoint-o2.adoc[]

endif::[]