
===== Registering the application in the Microsoft Entra Admin Center for OpenID Connect

*Login*

Sign in to the Microsoft Entra Admin Center using an account that has administrator permissions for your organization.  
`https://entra.microsoft.com`

*Navigation to "App registrations"*

* Select Entra ID on the far left  
* Navigate to "App registrations"  
* Register a new application  
* Click "New registration" (top menu)

*Enter application information*

* Name: Choose a name for the application. The name will be visible later. *Suggestion:* {application}-client-app  
* Supported account types: Decide whether the application should support only internal users (your own organization), 
external users, or multiple organizations. The default is "Single tenant".  
* Redirect‑URI:

  ** Click “Authentication” on the left side  
  ** Add a platform  
  ** Select “Web”  
  ** Enter the Redirect‑URIs — must match the value of `"redirect_uri"` in the `init_config.yaml`.

*Create*

* Click "Register".

*For application authentication:*

* On the left side, click “Certificates & secrets”  
* Create a new client secret → copy the value (it is displayed only once!)  
* Or alternatively upload a certificate.

*Configuration data:*

** Application ID: *Client ID*  
** Tenant ID: *Tenant ID*  
** Client secret: *Client Secret*, can be time‑limited  
** Redirect‑URI: *Redirect‑URI* redirect after successful login to {application}
```
Note: Record/copy these values for your application configuration in init_config.yaml.
```

*Additional settings*

* Click “Enterprise applications” on the far left  
* Select “{application}”  
* Click “Users and groups” in the left menu  
* Select “your_user_group”  
* Set the permission “User.Read” to “Delegated”
