
===== Registration Steps in Microsoft Entra Admin Center

*Login*

Sign in to the Microsoft Entra Admin Center with an account that has administrator rights for your organization (https://entra.microsoft.com)

*Navigation to "App Registrations"*

* Select Entra ID
* Navigate to "App Registrations".
* Register a new application
* Click on "New Registration" (at the top of the menu).

*Enter Application Information*

* Name: Choose a name for the application. *Suggestion*: {application}
* Supported account types: Decide whether the application should support only internal users (only your own organization), external users, or
multiple organizations. The default setting is "Single tenant".
*Note*: For {application} SharePoint integration, this setting is not relevant.
** *Redirect URL:* Must be provided (URL for redirecting to {application}, corresponds to the 'redirect_uri' in the `init_config.yaml`)
** For OpenID Connect additionally select "Web" and eetain the entry "company users only"

*Create*

* Click "Register".
* After registration you will receive:

** Application ID (Client ID)
** Directory ID (Tenant ID)
** Generate Client Secrets under "Certificates & Secrets"
```
Note: Record/copy these values for your application configuration in `init_config.yaml`.
```
