
==== SharePoint Integration via Microsoft Entra ID

The integration of SharePoint must be implemented via an API using the customer’s data.
In SharePoint, individual areas are referred to as sites. For example, when a new group is created in MS Teams, SharePoint automatically creates a corresponding SharePoint site linked to this group.

The necessary data for connecting {application} with credentials to the customer’s SharePoint includes:

* *Tenant ID:* The organization/tenant ID.
* *Application ID (Client):* The client ID of the application.
* *Secrets:* Access keys (can be time-limited)

These must be stored in the `init_config.yaml` file (see "Initial Configuration of the Application").
This information matches the configuration for "OpenID Connect Authentication with Microsoft Entra ID" or "SAML Authentication with Microsoft Entra ID."

If this data is *not* available, the {application} application must first be registered by the customer in the Microsoft Entra Admin Center.

ifeval::[{big-output} == 1]

include::chapter2-4-1-rag-sharepoint-o1_en.adoc[]

endif::[]

ifeval::[{big-output} == 1]

include::chapter2-4-1-rag-sharepoint-o2_en.adoc[]

endif::[]