
==== SAML Authentication with Microsoft Entra ID

SAML authentication with Microsoft Entra ID is always required when modern single sign-on functionality
and centralized identity management are needed for applications that rely on SAML (Security Assertion Markup Language) instead of OpenID Connect - 
optimally complementing a company’s overall identity and security concept.
SAML authentication with Microsoft Entra ID allows applications, especially legacy or specialized systems,
to be centrally and securely integrated with Microsoft’s identity management.

The necessary information for connecting {application} with the customer's SAML authentication are:

* *Tenant-ID:* The ID of the organization/tenant.
* *Anwendungs-ID:* The client ID of the application.
* *Client-Secrets* Access keys (can be time-limited)
* *Redirect‑URI:* Redirect after successful login to {application}

These details must be stored in the init_config.yaml file (see ‘Initial configuration of the application’).

If this data is *not* available, the {application} must first be registered by the customer in the Microsoft Entra Admin Center.
