
==== Sharepoint Anbindung über die Microsoft Entra ID (ehemals Azure Active Directory) gesicherte API

Die Anbindung von Sharepoint muss über eine API mit den Kundendaten erfolgen. 
In SharePoint werden einzelne Bereiche als Sites bezeichnet. Wenn z.B. eine neue Gruppe in MS Teams erstellt wird, erstellt SharePoint 
automatisch eine entsprechende SharePoint-Site, die mit dieser Gruppe verknüpft ist.

Die notwendigen Daten, für die Anbindung von {application} an Sharepoint des Kunden sind:

* **Tenant-ID:** Die ID des Mandanten, normalerweise eine GUID.
* **Client-ID:** Die Client-ID der Anwendung mit den erforderlichen Berechtigungen (Client-Secrets) für den Datenzugriff.
* **Client-Secrets:** Die SharePoint-Application-Berechtigungen für den Datenzugriff.

Diese werden in einen config file hinterlegt (siehe "Erstkonfiguration der Anwendung"). Sind diese Daten nicht vorhanden, 
muss die Applikation {application} vom Kunden erst in Microsoft Entra Admin Center registriert werden.

ifeval::[{big-output} == 1]

include::chapter2-4-1-rag-sharepoint-o1.adoc[]

endif::[]

ifeval::[{big-output} == 1]

include::chapter2-4-1-rag-sharepoint-o2.adoc[]

endif::[]