
To allow a registered application in the Microsoft Entra Admin Center to access SharePoint 
resources (e.g., lists, sites, files), some additional steps are required.

===== Managing SharePoint Permissions

*Adding API Permissions*

* Navigate to your app registration:
* Entra Admin Center → Entra ID → Applications → App Registrations → Select your application.
* Click on “API permissions”.
* Add permissions:
  ** Click "Add a permission".
  ** Select "Microsoft Graph"
  ** You must grant application permissions ("Application permissions"). The minimum required permission is "Sites.Read.All" or "Sites.Selected".

===== Granting Admin Consent

For your app to operate with these permissions, a tenant administrator must grant consent:
In the API permissions section, click "Grant admin consent for [your directory]".

===== Permissions on SharePoint 

The permissions alone on "Microsoft Graph" are not sufficient. Additionally, permissions must be explicitly granted to 
the individual SharePoint sites. 
The permission "Sites.Selected" only allows access to those sites for which permissions have been explicitly granted.

If permissions are to be granted to individual SharePoint sites, this can be done directly through the SharePoint Admin Center 
or the SharePoint user interface. 

However, if you need to manage many sites or different permissions, using the PowerShell module is more efficient.

*Step by Step PowerShell Module:*

Install Microsoft Graph PowerShell Module (if not already installed):
```
Install-Module Microsoft.Graph -Scope CurrentUser
```
You may need the role of "SharePoint Administrator" or Global Administrator to perform the PowerShell operations.

Sign In:
```
Connect-MgGraph -Scopes "Sites.Read.All", "Sites.Write.All", "Sites.Manage.All", "AppRoleAssignment.ReadWrite.All"
```

Save the App ID of registered application:
```
$appId = "YOUR-APP-ID"
```

Find the SharePoint Site ID:
```
$site = Get-MgSite -Filter "displayName eq 'NAME-OF-YOUR-SITE'"
$siteId = $site.Id
```

Grant permission on the site:
Example for granting Read permissions:
```
$permission = @{
    Roles = @("read")
    GrantedToIdentities = @(
        @{
            Application = @{
                Id = $appId
                DisplayName = "YOUR-APP-NAME"
            }
        }
    )
}
New-MgSitePermission -SiteId $siteId -BodyParameter $permission
```
