
=== Installation and Configuration

==== Initial Application Configuration

A *configuration package* is provided as a ZIP file, containing the basic configuration structure for {application}.
It includes the following file structure:

```
|_docker-compose.yaml
|_.env.example
|_configuration/
  |_config.yaml
  |_init/
    |_init_config.yaml
    |_authorization_roles.yaml
```

Optionally, a `Caddyfile.example` or a preconfigured `Caddyfile` for the reverse proxy configuration may also be included.

The following initial configurations must be performed:

- Create a `.env` file based on `.env.example`
- Configure the authentication method
- (optional) Configure RAG folder
- (optional) Configure SharePoint integration
- (optional) Configure reverse proxy

===== Set up environment variables 

The following values are configurable in `.env` File

|===
| Variable | Required | Description | Example value(s)

| `SHARED_FOLDER`
| Yes
| Path for shared directory
| `/opt/cgs-assist/shared`

| `JWT_SECRET_KEY`
| Required
| Hash for JWT creation (32-64 bytes)
| `hdhfh5jdnb7a9563b93f7099f6f0f4caa6cf63b88e8d3e7`

| `LOG_LEVEL`
| No
| Log level of the application (default: INFO)
| ERROR / WARNING / INFO

| `BRAVE_API_KEY`
| No
| API key for Brave web search integration
| 
|===

==== Deployment Guide (Step-by-Step)

Deployment of {application} is carried out in the following steps:

1. Prerequisites

- *Docker* is installed.
- The files from the *configuration package* are present in the working directory.
- (optional) A proxy configuration is prepared.

2. Configuration Data

- Collect and enter the required data (SharePoint integration, authentication, LLM-Provider) into `init_config.yaml` (see "Initial Application Configuration")

3. Login to Docker Hub Repository
  
- Use the provided read-access token: `docker login -u cgsmbh -p [ACCESS_TOKEN]`

4. Start the Application

- Start the application: `docker compose up -d`
- Wait for health check

5. Completion

- Test application accessibility in the browser

==== Update Process

The update process, performed by the customer, is as follows:

Recommendation: Before each update, create complete backups of the configuration and database (`SHARED_FOLDER`).

- Stop the application: `docker compose down`
- Update the configuration if necessary
- Download the new application images from Docker Hub: `docker compose pull`
	-- a Docker Hub login may be required (see "Deployment Guide (Step-by-Step)")
- Restart the application: `docker compose up -d`
- Check correct functionality

