

To allow a registered application in the Microsoft Entra Admin Center to access e-mail resources, 
additional steps are required.

===== Microsoft Graph – Manage Permissions

*Add API permissions*

* Navigate to your app registration:
* Entra Admin Center → Entra ID → Applications → App registrations → Select your application
* Click “API permissions”
* Add permissions:
** Click “Add a permission”
** Select “Microsoft Graph”
** You must assign Application permissions
*** "Mail.Read" (allows the app to read e-mails in mailboxes)

===== Grant admin consent

For your app to work with these permissions, a tenant administrator must approve them:
In the API permissions section, click “Grant admin consent for [Your Directory]”.

===== Microsoft Graph Mail Access – RBAC Setup

To ensure the application can only access a specific mailbox, an *Application Access Policy* 
is configured together with a *mail-enabled security group*.

====== Create a mail-enabled security group

In the *Microsoft / Exchange Admin Center*, create a *mail-enabled security group*.

*Example group configuration:*

* Name: <application>-RBAC-Mailbox-Group
* E-mail address of the group: <application>-rbac-mailbox@<customerdomain>

====== Add the mailbox to the group

Add the mailbox that the application should be allowed to access to the newly created group.

In our case: <application>@<customerdomain>

*Connect to Exchange Online*
PowerShell:
```powershell
Connect-ExchangeOnline
```
*Create Application Access Policy*
PowerShell:
```
New-ApplicationAccessPolicy `
  -AppId <APP_CLIENT_ID> `
  -PolicyScopeGroupId "<application>-rbac-mailbox@<customerdomain>" `
  -AccessRight RestrictAccess `
  -Description "RBAC access for <application> mail processing"
```
*Test the policy*
PowerShell:
```
Test-ApplicationAccessPolicy `
  -AppId <APP_CLIENT_ID> `
  -Identity <application>@<customerdomain>
```
*Check the mailbox*
PowerShell:
```
Get-Recipient -Identity <application>@<customerdomain> | Format-List Name, RecipientType, PrimarySmtpAddress
```
*Result:*
The application can only access mailboxes that are members of the defined security group.
In our case: – <application>@<customerdomain></customerdomain></application>