
name: Build IT-Handbook de html, pdf, docx

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
          - info
          - warning
          - debug
      pdfTheme:
        description: 'Asciidoctor PDF Theme'
        required: true
        default: 'CGS'
        type: choice
        options:
          - CGS
          - ARC
      outputType:
        description: 'Output type: 0=it-req(default), 1=small, 2=large'
        required: true
        default: '0'
        type: choice
        options:
          - 0
          - 1
          - 2
      version:
        description: 'Asciidoctor PDF Version'
        required: true
        default: '1.4.0'
        type: string

  
env:
  FILENAME: 'IT_HANDBOOK_DE_'
  FILEPATH: 'it_manual/de'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Asciidoctor & Asciidoctor-pdf
        run: |
          sudo gem install asciidoctor asciidoctor-pdf

      - name: Setup Pandoc
        uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: '3.1.6.2'

      - name: Install envsubst (gettext)
        run: sudo apt-get update && sudo apt-get install -y gettext

      - name: Define metadata variables
        run: |
         # Setze Titel/Autor/Anwendung dynamisch
          if [ "$PDF_THEME" = "ARC" ]; then
           echo "PRODUCT_TITLE=AI Audit Assist: IT-Handbuch" >> $GITHUB_ENV
           echo "AUTHOR=ARC Institute" >> $GITHUB_ENV
           echo "APPLICATION=AI Audit Assist" >> $GITHUB_ENV
           echo "ARC_ASSIST=1" >> $GITHUB_ENV
           echo "CGS_ASSIST=0" >> $GITHUB_ENV
          else
           echo "PRODUCT_TITLE=CGS Assist: Software für den Mittelstand - IT-Handbuch" >> $GITHUB_ENV
           echo "AUTHOR=CGS mbH" >> $GITHUB_ENV
           echo "APPLICATION=CGS Assist" >> $GITHUB_ENV
           echo "ARC_ASSIST=0" >> $GITHUB_ENV
           echo "CGS_ASSIST=1" >> $GITHUB_ENV
          fi
           echo "REVNUMBER=$VERSION" >> $GITHUB_ENV
           echo "BIG_OUTPUT=$OUTPUT_TYPE" >> $GITHUB_ENV
           # Set company static
           echo "COMPANY=Example AG" >> $GITHUB_ENV
          # Set date in German format
          echo "DATE=$(date '+%d.%m.%Y')" >> $GITHUB_ENV
        env:
         PDF_THEME: ${{ github.event.inputs.pdfTheme }}
         VERSION: ${{ github.event.inputs.version }}
         OUTPUT_TYPE: ${{ github.event.inputs.outputType }}

      - name: Fill metadata template
        run: |
         envsubst < "$FILEPATH/metadata.yml.tpl" > "$FILEPATH/metadata.yml"
         OUTPUT_NAME="${FILENAME}${PDF_THEME}_t_${BIG_OUTPUT}_v_${REVNUMBER}_d_${DATE}"
         echo "OUTPUT_NAME=$OUTPUT_NAME" >> $GITHUB_ENV
         
        env:
          FILENAME: ${{ env.FILENAME }}
          FILEPATH: ${{ env.FILEPATH }}
          PDF_THEME: ${{ github.event.inputs.pdfTheme }}
          BIG_OUTPUT: ${{ env.BIG_OUTPUT }}
          REVNUMBER: ${{ env.REVNUMBER }}
          DATE: ${{ env.DATE }}

      - name: Build HTML with Asciidoctor
        run: |
          asciidoctor \
          -D "$FILEPATH/" \
          -a product_title="$PRODUCT_TITLE" \
          -a revnumber="$REVNUMBER" \
          -a application="$APPLICATION" \
          -a author="$AUTHOR" \
          -a big-output="$BIG_OUTPUT" \
          -a company="$COMPANY" \
          -a date="$DATE" \
          -a cgs-assist="$CGS_ASSIST" \
          -a arc-assist="$ARC_ASSIST" \
          -a pdf-theme="$PDF_THEME" \
          -o "$OUTPUT_NAME.html" "$FILEPATH/index.adoc"
        env:
         FILEPATH: ${{ env.FILEPATH }}
         PRODUCT_TITLE: ${{ env.PRODUCT_TITLE }}
         REVNUMBER: ${{ env.REVNUMBER }}
         APPLICATION: ${{ env.APPLICATION }}
         AUTHOR: ${{ env.AUTHOR }}
         BIG_OUTPUT: ${{ env.BIG_OUTPUT }}
         COMPANY: ${{ env.COMPANY }}
         DATE: ${{ env.DATE }}
         CGS_ASSIST: ${{ env.CGS-ASSIST }}
         ARC_ASSIST: ${{ env.ARC-ASSIST }}
         PDF_THEME: ${{ github.event.inputs.pdfTheme }}
         OUTPUT_NAME: ${{ env.OUTPUT_NAME }}

      - name: Build PDF with Asciidoctor-pdf
        run: |
           asciidoctor-pdf \
           -D "$FILEPATH/" \
           -a product_title="$PRODUCT_TITLE" \
           -a revnumber="$REVNUMBER" \
           -a application="$APPLICATION" \
           -a author="$AUTHOR" \
           -a big-output="$BIG_OUTPUT" \
           -a company="$COMPANY" \
           -a date="$DATE" \
           -a cgs-assist="$CGS_ASSIST" \
           -a arc-assist="$ARC_ASSIST" \
           -a pdf-theme="$PDF_THEME" \
           -a pdf-themesdir=./themes \
           -o "$OUTPUT_NAME.pdf" "$FILEPATH/index.adoc"
        env:
         FILEPATH: ${{ env.FILEPATH }}
         PRODUCT_TITLE: ${{ env.PRODUCT_TITLE }}
         REVNUMBER: ${{ env.REVNUMBER }}
         APPLICATION: ${{ env.APPLICATION }}
         AUTHOR: ${{ env.AUTHOR }}
         BIG_OUTPUT: ${{ env.BIG_OUTPUT }}
         COMPANY: ${{ env.COMPANY }}
         DATE: ${{ env.DATE }}
         CGS_ASSIST: ${{ env.CGS-ASSIST }}
         ARC_ASSIST: ${{ env.ARC-ASSIST }}
         PDF_THEME: ${{ github.event.inputs.pdfTheme }}
         OUTPUT_NAME: ${{ env.OUTPUT_NAME }}

      - name: Build DOCX with Pandoc von html
        run: |
          pandoc "$FILEPATH/$OUTPUT_NAME.html" \
          --from=html \
          --to=docx \
          --standalone \
          --reference-doc=../../themes/style-reference.docx \
          --metadata-file="$FILEPATH/metadata.yml" \
          --resource-path="$FILEPATH"  \
          -o "$FILEPATH/$OUTPUT_NAME.docx"
        env:
          FILEPATH: ${{ env.FILEPATH }}
          OUTPUT_NAME: ${{ env.OUTPUT_NAME }}
      
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.OUTPUT_NAME }}
          path: |
            ${{ env.FILEPATH }}/${{ env.OUTPUT_NAME }}.pdf
            ${{ env.FILEPATH }}/${{ env.OUTPUT_NAME }}.html
            ${{ env.FILEPATH }}/${{ env.OUTPUT_NAME }}.docx
            ${{ env.FILEPATH }}/image/*
