name: Build Catalog

on:
  workflow_dispatch:
    inputs:
      UC1:
        description: "Grundsatz - Dokumentenabgleich"
        required: false
        type: boolean
      UC2:
        description: "Grundsatz - Textanonymisierung"
        required: false
        type: boolean
      UC3:
        description: "CGS Intern - Vorlage zur Use Case-Erstellung"
        required: false
        type: boolean
        
jobs:
  show-selection:
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Ausgewählt:"
            if [ "${{ github.event.inputs.UC1}}" = "true" ]; then echo " - UC1 Grundsatz - Dokumentenabgleich"; fi
            if [ "${{ github.event.inputs.UC2 }}" = "true" ]; then echo " - UC2 Grundsatz - Textanonymisierung"; fi
            if [ "${{ github.event.inputs.UC3 }}" = "true" ]; then echo " - UC3 CGS Intern - Vorlage zur Use Case-Erstellung"; fi
