name: Build Catalog

on:
  workflow_dispatch:
    inputs:
      UC1:
        description: "UC1"
        required: false
        type: boolean
      UC2:
        description: "UC2"
        required: false
        type: boolean
      UC3:
        description: "UC3"
        required: false
        type: boolean
        
jobs:
  show-selection:
    runs-on: ubuntu-latest
    steps:
        - run: |
            echo "Ausgewählt:"
            if [ "${{ github.event.inputs.UC1}}" = "true" ]; then echo " - UC1"; fi
            if [ "${{ github.event.inputs.UC2 }}" = "true" ]; then echo " - UC2"; fi
            if [ "${{ github.event.inputs.UC3 }}" = "true" ]; then echo " - UC3"; fi
